### ISSUE TITLE
Error to install on Python 3.5.x

### ISSUE THREAD

**Issue by rhenter** [lamenezes/simple-model#33]
```bash
~
$ pip install pysimplemodel
Collecting pysimplemodel
  Using cached https://files.pythonhosted.org/packages/b9/71/f76a14368b433109082356db0bc9e83bfd1627214fa88966b846ec3e1a59/pysimplemodel-2.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4j/cvmm9p350v51lnzzhtjchxd40000gn/T/pip-install-16w8dnhi/pysimplemodel/setup.py", line 6, in <module>
        from simple_model.__version__ import __version__
      File "/private/var/folders/4j/cvmm9p350v51lnzzhtjchxd40000gn/T/pip-install-16w8dnhi/pysimplemodel/simple_model/__init__.py", line 2, in <module>
        from .builder import model_builder, model_many_builder
      File "/private/var/folders/4j/cvmm9p350v51lnzzhtjchxd40000gn/T/pip-install-16w8dnhi/pysimplemodel/simple_model/builder.py", line 3, in <module>
        from .models import Model
      File "/private/var/folders/4j/cvmm9p350v51lnzzhtjchxd40000gn/T/pip-install-16w8dnhi/pysimplemodel/simple_model/models.py", line 5, in <module>
        from .fields import ModelField, Unset
      File "/private/var/folders/4j/cvmm9p350v51lnzzhtjchxd40000gn/T/pip-install-16w8dnhi/pysimplemodel/simple_model/fields.py", line 24
        return (f'ModelField(model_class={self.model_class!r}, name={self.name!r}, '
                                                                                   ^
    SyntaxError: invalid syntax
```

**Comment by lamenezes** [comment]
@rhenter infelizmente o simple-model não suporta mais o python 3.5 mesmo pq a lib usa umas features de type hints que só existem na versão 3.6 para frente.
